# Generated by Django 5.2.10 on 2026-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='상세페이지 URL')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='썸네일 URL')),
                ('title', models.CharField(max_length=255, verbose_name='물품명')),
                ('location', models.CharField(max_length=100, verbose_name='보관장소/지역')),
                ('price', models.BigIntegerField(default=0, verbose_name='최저입찰가')),
                ('description', models.TextField(blank=True, verbose_name='물품 상세설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
            ],
            options={
                'db_table': 'gold_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
